Documentation:
  Enabled: false
Style/DotPosition:
  EnforcedStyle: trailing
AllCops:
  TargetRubyVersion: 2.2
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - db/**
    - config/**
    - script/**
